
save_image_subtitle_ocr_success = "save_image_subtitle_ocr_success"
save_image_subtitle_ocr_failed = "save_image_subtitle_ocr_failed"

image_subtitle_area_predict_success = "image_subtitle_area_predict_success"
image_subtitle_area_predict_failed = "image_subtitle_area_predict_failed"

image_subtitle_area_predict_box_valid = "image_subtitle_area_predict_box_valid"
image_subtitle_area_predict_box_invalid = "image_subtitle_area_predict_box_invalid"

image_subtitle_area_croped_success = "image_subtitle_area_croped_success"
image_subtitle_area_croped_failed = "image_subtitle_area_croped_failed"

image_subtitle_ocr_success = "image_subtitle_ocr_success"
image_subtitle_ocr_failed = "image_subtitle_ocr_failed"
image_subtitle_ocr_no_data = "image_subtitle_ocr_no_data"

save_video_subtitle_success = "save_video_subtitle_success"
save_video_subtitle_failed = "save_video_subtitle_failed"