database:
  host: 192.168.0.106
  port: 3306
  username: root
  password: 1111
  db-dir: D:/SQLite3_DB/
  db-name: subtitle_ocr
  charset: utf8
  max-connection-size: 20
  init-connection-size: 2
  max-idle-size: 5
  blocking-if-no-connection: True

